import type { Facility } from '../types/facility'

export const FACILITIES: Facility[] = [
  {
    id: 'fac_matugga',
    name: 'Matugga GMP Bio-Plant',
    shortName: 'Matugga GMP',
    code: 'MAT-GMP',
    type: 'MANUFACTURING',
    location: 'Matugga Facility',
    region: 'Wakiso District',
    isGmpCertified: true,
    complianceLevel: 'WHO_GMP_GRADE_A',
    status: 'ACTIVE',
    statusLabel: 'GMP Active',
    currency: 'USD',
    timezone: 'Africa/Kampala',
    activeLinesCount: 12,
    staffOnDuty: 847,
    badgeText: 'GMP Certified Plant',
    headlineStatus: '12 bioreactors running · 1 temp deviation monitored',
  },
  {
    id: 'fac_kakiika',
    name: 'Kakiika Clinical & Trials Unit',
    shortName: 'Kakiika Clinical',
    code: 'KAK-CLINIC',
    type: 'CLINICAL',
    location: 'Kakiika Hospital Campus',
    region: 'Mbarara City',
    isGmpCertified: true,
    complianceLevel: 'CLINICAL_TRIAL_GCP',
    status: 'ACTIVE',
    statusLabel: 'GCP Live',
    currency: 'USD',
    timezone: 'Africa/Kampala',
    activeLinesCount: 6,
    staffOnDuty: 312,
    badgeText: 'GCP Clinical Trial Site',
    headlineStatus: '4 Phase-III trials active · 100% patient adherence',
  },
  {
    id: 'fac_nakaseke',
    name: 'Nakaseke Bio-Agro Extraction Farm',
    shortName: 'Nakaseke Bio-Agro',
    code: 'NAK-AGRO',
    type: 'AGRICULTURE',
    location: 'Nakaseke Botanical Reserve',
    region: 'Nakaseke District',
    isGmpCertified: false,
    complianceLevel: 'ORGANIC_GAP',
    status: 'ACTIVE',
    statusLabel: 'Harvest Active',
    currency: 'UGX',
    timezone: 'Africa/Kampala',
    activeLinesCount: 8,
    staffOnDuty: 420,
    badgeText: 'GAP Certified Organic',
    headlineStatus: '8 botanical harvest zones · 24 tons raw yield today',
  },
  {
    id: 'fac_corporate',
    name: 'Dei Group Corporate Holding',
    shortName: 'Global HQ',
    code: 'DEI-HQ',
    type: 'CORPORATE',
    location: 'Dei Towers, Nakasero',
    region: 'Kampala City',
    isGmpCertified: false,
    complianceLevel: 'ISO_9001',
    status: 'ACTIVE',
    statusLabel: 'Global Holding',
    currency: 'USD',
    timezone: 'Africa/Kampala',
    activeLinesCount: 26,
    staffOnDuty: 1579,
    badgeText: 'Dei Global Conglomerate',
    headlineStatus: 'All 3 facilities online · Consolidated reporting live',
  },
]
